# Generated by Django 3.2.4 on 2021-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='asuntoMensaje',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Asunto Mensaje'),
        ),
    ]
