# Generated by Django 3.2.4 on 2021-06-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20210618_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='MensajeContacto',
        ),
    ]
