# Generated by Django 3.2.4 on 2021-06-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_rename_contacto_mensajecontacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensajeContacto',
        ),
    ]
