# Generated by Django 3.2.4 on 2021-06-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0005_delete_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuntoMensaje', models.CharField(max_length=100, verbose_name='Asunto Mensaje')),
                ('nombreContacto', models.CharField(max_length=40, verbose_name='Nombre de Contacto')),
                ('correoContacto', models.CharField(max_length=100, verbose_name='Correo de Contacto')),
                ('fonoContacto', models.IntegerField(verbose_name='Telefono de Contacto')),
                ('mensaje', models.CharField(max_length=500, verbose_name='Mensaje')),
            ],
        ),
    ]
