# Generated by Django 3.2.4 on 2021-06-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_alter_mensajecontacto_fonocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='fonoContacto',
            field=models.CharField(max_length=14, verbose_name='Telefono de Contacto'),
        ),
    ]
